name: Build and Push Fake-Zertifikatshop-API (release) Image

on:
  release:
    types: [published]

jobs:
  upload-assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0

      - name: Get Release ID from tag
        run: .gitea/scripts/get-release-id.sh "${{ github.event.release.tag_name }}"

      - name: Restore Docker cache
        uses: https://git.0xmax42.io/actions/cache@v1
        with:
          key: buildx-main
          paths: |
            /tmp/.buildx-cache

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true
          buildkitd-flags: --debug

      - name: Login to Gitea Docker Registry
        env:
          REGISTRY: git.0xmax42.io
          USERNAME: ${{ secrets.PACKAGE_USER }}
          PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          echo "$PASSWORD" | docker login $REGISTRY --username "$USERNAME" --password-stdin

      - name: Build Docker Image
        run: |
          docker buildx build \
            --tag git.0xmax42.io/maxp/fake-zertifikatshop-api:${{ github.event.release.tag_name }} \
            --tag git.0xmax42.io/maxp/fake-zertifikatshop-api:latest \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max \
            --builder ${{ steps.buildx.outputs.name }} \
            --push \
            --progress=plain \
            .
